module PostProcessors
  # Add an autogenerated notice to generated files.
  class AutogenerateLabeler
  	ANCHOR1 = "\n## ".freeze
  	ANCHOR2 = "---\n\n".freeze

  	class << self
  		def label!(content, template)
	      notice =
	        <<~EOF
	        <!--
	             THIS FILE IS AUTOGENERATED!

	             To make changes please edit the template located at:

	             #{template.gsub(ROOT_DIR, "").split("/")[3..-1].join("/")}
	        -->
	        EOF

	      if content.include?(ANCHOR1)
	      	content.sub!(/#{ANCHOR1}/, "\n#{notice}#{ANCHOR1}")
	      elsif content.include?(ANCHOR2)
	      	content.sub!(/#{ANCHOR2}/, "#{ANCHOR2}#{notice}\n")
	      else
	      	notice + content
	      end
	    end
	  end
	end
end