module PostProcessors
  # Add an autogenerated notice to generated files.
  class AutogenerateLabeler
  	ANCHOR1 = "\n## ".freeze
  	ANCHOR2 = "---\n\n".freeze

  	class << self
  		def label!(content, template)
  			case File.extname(template.gsub(".erb", ""))
  			when ".md"
  				label_md!(content, template)
  			when ".tf"
  				label_tf!(content, template)
  			else
  				content
  			end
	    end

	  	private
	  		def label_md!(content, template)
	  			notice =
		        <<~EOF
		        <!--
		        #{generate_notice(template).indent(4)}
		        -->
		        EOF

		      if content.include?(ANCHOR1)
		      	content.sub!(/#{ANCHOR1}/, "\n#{notice}#{ANCHOR1}")
		      elsif content.include?(ANCHOR2)
		      	content.sub!(/#{ANCHOR2}/, "#{ANCHOR2}#{notice}\n")
		      else
		      	notice + "\n\n" + content
		      end
	  		end

	  		def label_tf!(content, template)
	  			notice =
		        <<~EOF
		        /*
		        #{generate_notice(template).indent(4)}
		        */
		        EOF

		      notice + content
	  		end

	  		def generate_notice(template)
	  			notice =
		  			<<~EOF
	         	THIS FILE IS AUTOGENERATED!

	         	To make changes please edit the template located at:

	          #{template.gsub(ROOT_DIR, "").split("/")[3..-1].join("/")}
		        EOF

		      notice.strip
	      end
	  end
	end
end